# Generated by Django 4.2.20 on 2025-04-12 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('gender', models.CharField(blank=True, max_length=50, null=True, verbose_name='Gênero')),
                ('address_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('address_state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('address_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='País')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('linkedin_profile', models.URLField(blank=True, null=True, verbose_name='Perfil LinkedIn')),
                ('academic_formation', models.TextField(blank=True, null=True, verbose_name='Grau de Formação')),
                ('institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instituição')),
                ('course', models.CharField(blank=True, max_length=255, null=True, verbose_name='Curso')),
                ('graduation_year', models.IntegerField(blank=True, null=True, verbose_name='Ano de Conclusão')),
                ('previous_position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Posição Anterior')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Empresa')),
                ('work_period_start', models.DateField(blank=True, null=True, verbose_name='Início do Período de Trabalho')),
                ('work_period_end', models.DateField(blank=True, null=True, verbose_name='Fim do Período de Trabalho')),
                ('main_responsibilities', models.TextField(blank=True, null=True, verbose_name='Principais Responsabilidades')),
                ('technical_skills', models.TextField(blank=True, null=True, verbose_name='Habilidades Técnicas')),
                ('interpersonal_skills', models.TextField(blank=True, null=True, verbose_name='Habilidades Interpessoais')),
                ('area_of_interest', models.CharField(blank=True, max_length=255, null=True, verbose_name='Área de Interesse')),
                ('desired_contract_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Contrato Desejado')),
                ('professional_summary', models.TextField(blank=True, null=True, verbose_name='Resumo Profissional')),
                ('relevant_projects', models.TextField(blank=True, null=True, verbose_name='Projetos Relevantes')),
                ('languages', models.TextField(blank=True, null=True, verbose_name='Idiomas')),
                ('curriculum_attachment', models.FileField(blank=True, null=True, upload_to='curriculums/', verbose_name='Anexo do Currículo')),
                ('groups', models.ManyToManyField(related_name='customuser_groups', to='auth.group', verbose_name='Grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
