# Generated by Django 4.2.20 on 2025-04-12 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('ramo', models.CharField(choices=[('tecnologia', 'Tecnologia'), ('suporte', 'Suporte'), ('administrativo', 'Administrativo'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('financeiro', 'Financeiro'), ('engenharia', 'Engenharia'), ('marketing', 'Marketing'), ('vendas', 'Vendas'), ('juridico', 'Jurídico'), ('recursos_humanos', 'Recursos Humanos'), ('logistica', 'Logística'), ('administracao', 'Administração'), ('comunicacao', 'Comunicação'), ('arte_design', 'Arte e Design'), ('turismo', 'Turismo'), ('agropecuaria', 'Agropecuária'), ('construcao_civil', 'Construção Civil'), ('transporte', 'Transporte'), ('telecomunicacoes', 'Telecomunicações'), ('energia', 'Energia'), ('alimentacao', 'Alimentação'), ('agronegocio', 'Agronegócio'), ('outros', 'Outros')], default='ESCOLHA', max_length=50)),
                ('formacao_academica', models.CharField(choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('tecnico', 'Técnico'), ('graduacao', 'Graduação'), ('pos_graduacao', 'Pós-Graduação'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado'), ('outros', 'Outros')], default='outros', max_length=20)),
                ('tipo_contrato', models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'PJ'), ('Freelancer', 'Freelancer'), ('Temporário', 'Temporário')], max_length=15)),
                ('modelo_trabalho', models.CharField(choices=[('remoto', 'Remoto'), ('hibrido', 'Híbrido'), ('presencial', 'Presencial')], default='presencial', max_length=15)),
                ('descricao', models.TextField()),
                ('requisitos', models.TextField()),
                ('diferenciais', models.TextField()),
                ('responsabilidades', models.TextField()),
                ('beneficios', models.TextField(blank=True, null=True)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('salario', models.CharField(blank=True, help_text="Informe a faixa salarial no formato: '1200 - 2000'", max_length=50, null=True, verbose_name='Faixa Salarial')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('encerrada', 'Encerrada')], default='ativa', max_length=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.empresa')),
            ],
        ),
    ]
